services:
  go:
    build:
      context: .
      dockerfile: ./infra/dev/go/Dockerfile
    volumes:
      - ./backend:/backend
    environment:
      TZ: Asia/Tokyo
    tty: true
    ports:
      - 8080:8080
  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
